version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: happywed-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - happywed-network
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: happywed-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: happywed
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - happywed-network

  nginx:
    image: nginx:latest
    container_name: happywed-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - happywed-network

volumes:
  db-data:

networks:
  happywed-network:
